application:
  port: 8082
  host: 127.0.0.1
rabbitmq:
  uri: "amqp://guest:guest@localhost:5672"
postgres:
  host: "localhost"
  port: 5432
  username: "username"
  password: "password"
  database_name: "db"
  schema_name: "public"
