application:
  port: 8081
  host: 0.0.0.0
  base_url: "http://0.0.0.0"
rabbitmq:
  gateway_url: "amqp://guest:guest@localhost:5672"
  storage_url: "amqp://guest:guest@localhost:5672"
  gateway_queue: "gateway"
  transaction_queue: "storage"
  reply_queue: "rpc_reply"
  storage_exchange: "storage"
redis:
  uri: "redis://127.0.0.1:6379"
